version: 0.2
phases:
  pre_build:
    commands:
      - echo Prebuild started on `date`
      - echo Build environment is $BUILD_ENV
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
