version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Prebuild started on `date`
      - echo Build environment is $BUILD_ENV
  build:
    commands:
      - echo Build started on `date`
      - npm run build:mura.js
  post_build:
    commands:
      - echo Build completed on `date`
