version: 0.2
phases:
  pre_build:
    commands:
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  build:
    commands:
      - npm install
  post_build:
    commands:
      - echo Publishing to npm...
      - |-
        set -e
        if [ "$BUILD_ENV" = "dev" ]; then
          npm run publish:rc
        elif [ "$BUILD_ENV" = "prod" ]; then
          npm run publish:prod
        fi